version: "3.7"

services: 
  db:
    image: postgres
    labels:
      - traefik.enable=false
    environment:
      POSTGRES_USER: sophia
      POSTGRES_DB: sophia
      POSTGRES_PASSWORD: sophia
    volumes:
      - /var/db/bytecom/datadir:/var/lib/postgresql/data
    networks:
      - internal
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - internal
  app:
    depends_on: 
      - db
    build: .
    command: npm start
    ports: 
      - "80:3000"
    volumes: 
      - .:/usr/app
    networks:
      - internal
networks:
  internal: